package com.csse3200.game.utils;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;

public class GsonJsonUtils {
    // This class was generated by ChatGPT
    private final Gson gson;

    public GsonJsonUtils() {
        this.gson = new Gson();
    }

    // Converts a HashMap to a JSON string
    public String hashMapToJson(HashMap<String, Long> map) {
        return gson.toJson(map);
    }

    // Converts a JSON string back to a HashMap
    public HashMap<String, Long> jsonToHashMap(String json) {
        Type type = new TypeToken<HashMap<String, Long>>() {}.getType();
        return gson.fromJson(json, type);
    }
}
