package com.csse3200.game.ui.cutscene;

import com.badlogic.gdx.graphics.Pixmap;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.scenes.scene2d.Actor;
import com.badlogic.gdx.scenes.scene2d.ui.Image;
import com.badlogic.gdx.scenes.scene2d.ui.Stack;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.scenes.scene2d.ui.TextButton;
import com.badlogic.gdx.scenes.scene2d.utils.ChangeListener;
import com.csse3200.game.areas.GameArea;
import com.csse3200.game.services.ServiceLocator;
import com.csse3200.game.ui.UIComponent;
import com.csse3200.game.ui.cutscene.CutsceneReaderComponent.TextBox;
import com.github.tommyettinger.textra.TypingLabel;

import java.util.List;

/**
 * Component that can be attached to an entity in order to render necessary visual elements for
 * a cutscene (text boxes, buttons, background). Also handles button presses for progressing
 * cutscene
 */
public class CutsceneDisplay extends UIComponent {
    /**
     * Ordered list of text boxes to be displayed in cutscene
     */
    private final List<TextBox> textBoxList;
    /**
     * Reference to the game area the entity this component is attached to is inside of
     */
    private final GameArea area;
    /**
     * ID of the next game area to load after cutscene finishes
     */
    private final String nextAreaID;
    /**
     * A reference to what text box is currently being displayed
     */
    private int curTextBox = 0;
    /**
     * Root table to be rendered
     */
    private Stack rootStack;
    /**
     * Text table inside of root table
     */
    private Table textTable;
    /**
     * Table to hold background image inside of root table
     */
    private Table imageTable;
    /**
     * Texture for background behind the text
     */
    private Texture textBgTexture;

    /**
     * Initialises the UI for the cutscene
     *
     * @param textBoxList An ordered list of all text boxes to show, generated by a
     *                    CutsceneReaderComponent ideally
     * @param area        The instance of the GameArea the entity this component is attached to
     *                    is apart of
     * @param nextAreaID  The ID of the next GameArea to load after the cutscene is finished
     */
    public CutsceneDisplay(List<TextBox> textBoxList, GameArea area, String nextAreaID) {
        this.textBoxList = textBoxList;
        this.area = area;
        this.nextAreaID = nextAreaID;
    }

    /**
     * Generates a stack which is rendered to the UI. The stack has two layers:
     * <p>
     * - A background
     * <p>
     * - A text box (containing text and button)
     * <p>
     * Also attaches an event listener to the button in the text box to progress to next text boss,
     * and load next GameArea when necessary
     */
    @Override
    public void create() {
        super.create();

        // Create root stack - fills screen
        rootStack = new Stack();
        rootStack.setFillParent(true);

        // Create background layer
        imageTable = new Table();
        rootStack.add(imageTable);

        // Create UI table
        Table uiTable = new Table();
        uiTable.bottom();
        rootStack.add(uiTable);

        // Create text box container
        Table textBoxContainer = new Table();

        // Create transparent background for text box
        Pixmap pixmap = new Pixmap(1, 1, Pixmap.Format.RGBA8888);
        pixmap.setColor(0, 0, 0, 0.5f);
        pixmap.fill();
        textBgTexture = new Texture(pixmap);
        pixmap.dispose();
        textBoxContainer.setBackground(new Image(textBgTexture).getDrawable());

        // Add text table to text container
        textTable = new Table();
        textBoxContainer.add(textTable).expandX().fillX().pad(20f);

        // Add button to text container
        TextButton progressButton = new TextButton("Next", skin);
        textBoxContainer.add(progressButton).pad(20f);

        // Add text box container to UI table
        uiTable.add(textBoxContainer).expandX().fillX().pad(20f);

        // Create listener for progress button
        progressButton.addListener(
                new ChangeListener() {
                    @Override
                    public void changed(ChangeEvent event, Actor actor) {
                        // Do nothing for now if we are on last index
                        if (curTextBox == textBoxList.size() - 1) {
                            area.trigger("cutsceneFinished", nextAreaID, null);
                        } else {
                            nextTextBox();
                        }
                    }
                }
        );

        // Draw the first text box
        setTextBox();

        // Add stack to scene
        stage.addActor(rootStack);
    }

    /**
     * Updates the UI with information from the current text box. It sets the text to be typed out
     * in the text box, and a new background for the cutscene, if found.
     */
    private void setTextBox() {
        // Clear text table
        if (textTable != null) {
            textTable.clear();
        }
        // Get text box from list
        TextBox textBox = textBoxList.get(curTextBox);

        // Generate label
        TypingLabel text = new TypingLabel(textBox.text(), skin);
        // Add label to text table
        textTable.add(text).expandX().fillX().pad(15f);

        // If background associated with new text box is null, don't change
        if (textBox.background() != null) {
            imageTable.clear();
            Image background =
                    new Image(ServiceLocator.getResourceService().getAsset(textBox.background(),
                            Texture.class));
            background.setFillParent(true);
            imageTable.addActor(background);
        }
    }

    /**
     * Method that updates the current text box points to the next text box
     */
    private void nextTextBox() {
        curTextBox++;
        setTextBox();
    }

    /**
     * Draw is not used by an instance of this component as the Stack is handled by Scene2D
     * @param batch Batch to render to.
     */
    @Override
    protected void draw(SpriteBatch batch) {
        // Handled by Scene2D
    }

    /**
     * Correctly removes all widgets registered in the root stack object
     */
    @Override
    public void dispose() {
        super.dispose();

        if (rootStack != null) {
            rootStack.remove();
        }
        if (textBgTexture != null) {
            textBgTexture.dispose();
        }
    }
}
