name: Build macOS PKG

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build JAR with Gradle
        run: |
          chmod +x gradlew
          ./gradlew desktop:dist
      
      - name: Create macOS PKG
        run: |
          jpackage \
            --input desktop/build/libs \
            --name "Cyberescape2077" \
            --main-jar desktop-1.0.jar \
            --main-class com.csse3200.game.desktop.DesktopLauncher \
            --type pkg \
            --app-version 1.0 \
            --vendor "CSSE3200"
      
      - name: Upload PKG artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-pkg
          path: "*.pkg"
      
      - name: Create Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: "*.pkg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
